#!/usr/bin/env bash
# Starts the ClinicOps backend + frontend as Docker containers.
#
# Usage:
#   ./start.sh           # build images if needed, run in foreground
#   ./start.sh -d        # build images if needed, run detached
#   ./start.sh --rebuild # force a rebuild of both images before starting
#   ./start.sh --stop    # stop and remove the containers

set -euo pipefail

cd "$(dirname "$0")"

if ! command -v docker >/dev/null 2>&1; then
  echo "error: docker is required but not installed" >&2
  exit 1
fi

if docker compose version >/dev/null 2>&1; then
  DC=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  DC=(docker-compose)
else
  echo "error: docker compose plugin or docker-compose binary is required" >&2
  exit 1
fi

DETACH=""
REBUILD=""
STOP=""

for arg in "$@"; do
  case "$arg" in
    -d|--detach) DETACH="-d" ;;
    --rebuild)   REBUILD="1" ;;
    --stop|down) STOP="1" ;;
    -h|--help)
      sed -n '2,9p' "$0"
      exit 0
      ;;
    *)
      echo "unknown flag: $arg" >&2
      exit 2
      ;;
  esac
done

if [[ -n "$STOP" ]]; then
  "${DC[@]}" down --remove-orphans
  exit 0
fi

# Auto-generate a .env file with strong random secrets if one does not exist.
# docker compose reads .env automatically — these override the blank defaults
# in docker-compose.yml so the backend starts cleanly in NODE_ENV=production.
if [[ ! -f .env ]]; then
  echo ">> No .env found — generating random secrets..."
  JWT_SECRET_VAL=$(openssl rand -hex 32)
  AES_KEY_VAL=$(openssl rand -base64 32)
  cat > .env <<EOF
# Auto-generated by start.sh — do NOT commit this file.
JWT_SECRET=${JWT_SECRET_VAL}
CLINICOPS_AES_KEY=${AES_KEY_VAL}
EOF
  echo ">> .env created (JWT_SECRET + CLINICOPS_AES_KEY)."
fi

BUILD_FLAG=(--build)
if [[ -n "$REBUILD" ]]; then
  "${DC[@]}" build --no-cache
  BUILD_FLAG=()
fi

echo ""
echo ">> Starting ClinicOps stack..."
echo "   Frontend UI:     http://localhost:5173"
echo "   Backend API:     http://localhost:4000/api"
echo "   Health check:    http://localhost:4000/health"
echo ""

if [[ -n "$DETACH" ]]; then
  "${DC[@]}" up "${BUILD_FLAG[@]}" -d
  echo ">> Stack is running in the background."
  echo "   Tail logs:  ${DC[*]} logs -f"
  echo "   Stop:       ./start.sh --stop"
else
  echo ">> Press Ctrl+C to stop."
  echo ""
  "${DC[@]}" up "${BUILD_FLAG[@]}"
fi
